export const COUNTRIES = [
  "South Africa", "Worldwide", "United States", "United Kingdom", "Australia", "Canada",
  "Germany", "France", "Netherlands", "Belgium", "Sweden", "Norway", "Denmark",
  "Finland", "Switzerland", "Austria", "New Zealand", "Ireland", "Singapore",
  "United Arab Emirates", "Saudi Arabia", "India", "Brazil", "Mexico", "Japan",
  "South Korea", "China", "Hong Kong", "Taiwan", "Malaysia", "Thailand",
  "Philippines", "Indonesia", "Vietnam", "Nigeria", "Kenya", "Egypt", "Israel",
  "Poland", "Czech Republic", "Hungary", "Romania", "Bulgaria", "Croatia",
  "Slovenia", "Slovakia", "Lithuania", "Latvia", "Estonia", "Luxembourg",
  "Malta", "Cyprus", "Iceland", "Liechtenstein", "Monaco", "Andorra",
  "San Marino", "Vatican City", "Russia", "Ukraine", "Belarus", "Moldova",
  "Georgia", "Armenia", "Azerbaijan", "Kazakhstan", "Uzbekistan", "Turkmenistan",
  "Kyrgyzstan", "Tajikistan", "Mongolia", "Pakistan", "Bangladesh", "Sri Lanka",
  "Nepal", "Bhutan", "Maldives", "Afghanistan", "Iran", "Iraq", "Syria",
  "Lebanon", "Jordan", "Palestine", "Kuwait", "Bahrain", "Qatar", "Oman",
  "Yemen", "Libya", "Tunisia", "Algeria", "Morocco", "Mauritania", "Mali",
  "Burkina Faso", "Niger", "Chad", "Sudan", "Eritrea", "Djibouti", "Somalia",
  "Ethiopia", "Uganda", "Tanzania", "Rwanda", "Burundi", "Democratic Republic of the Congo",
  "Republic of the Congo", "Gabon", "Equatorial Guinea", "Cameroon", "Central African Republic",
  "South Sudan", "Zambia", "Zimbabwe", "Botswana", "Namibia", "Angola", "Mozambique",
  "Malawi", "Madagascar", "Comoros", "Seychelles", "Mauritius", "Lesotho", "Eswatini",
  "Gambia", "Senegal", "Guinea-Bissau", "Guinea", "Sierra Leone", "Liberia",
  "Ivory Coast", "Ghana", "Togo", "Benin", "Nigeria", "Cameroon", "Cape Verde"
];
